services:
  - type: web
    name: notes-vault-backend
    runtime: docker
    dockerfilePath: ./Backend/Notes-Vault/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    database:
      name: notesvaultdb
      postgresVersion: 14

  - type: web
    name: notes-vault-frontend
    runtime: docker
    dockerfilePath: ./Frontend/notes-vault/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://notes-vault-backend.onrender.com