services:
  - type: web
    name: notes-vault-backend
    runtime: docker
    dockerfilePath: Backend/Notes-Vault/Dockerfile
    buildCommand: cd Backend/Notes-Vault && ./mvnw clean package -DskipTests
    startCommand: java -jar Backend/Notes-Vault/target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    database:
      name: notesvaultdb
      postgresVersion: 16

  - type: web
    name: notes-vault-frontend
    runtime: docker
    dockerfilePath: ./Frontend/notes-vault/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://notes-vault-backend.onrender.com